name: Daily Scholar Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 KST (UTC 자정)
  workflow_dispatch:      # 수동 실행용, 들여쓰기와 문법 정확히!

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas openpyxl

- name: Run scraper
  run: |
    python scholar_scraper.py

- name: Commit and push updated file
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add .
    git commit -m "자동 업데이트 논문 데이터" || echo "No changes to commit"
    git push https://${{ secrets.GH_TOKEN }}@github.com/SmartCho-Phd/Scholar-paper-scraper.git main




