name: Daily Scholar Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 기준 자정(한국 오전 9시)에 매일 실행
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas openpyxl

      - name: Run scraper
        run: |
          python scholar_scraper.py

    - name: Commit and Push updated file
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add .
    git commit -m "자동 업데이트 논문 데이터"
    git push https://${{ secrets.GH_TOKEN }}@github.com/<유저명>/<레포지토리명>.git main
